### ISSUE TITLE
Получение настроек исключений выполняется для каждого объекта при формировании тестов

### ISSUE THREAD

**Issue by 1cgh** [alexandr-yang/yaxunit-smoke#2]
AS IS
Получение настроек исключений выполняется для каждого объекта при формировании тестов.
Если формирование исключений достаточно "тяжелое", то это сильно замедляет формирование тестов.

TO BE
Настройки исключений должны рассчитываться один раз и переиспользоваться.

**Comment by alexandr-yang** [comment]
В будущем настройки планируется хранить в файле, yaxunit будет его читать и хранить их в контексте.
Доработки в yaxunit уже сделаны, ждем релиз.
